export const CONFIG = {
  ROOM_MAX_CLIENTS: 8,
  DEFAULT_BATTLE_HP: 500,
  DEFAULT_SESSION_HP: 40,
  SESSION_HP_LOSS: 5,
  TICK_RATE: 10,
  CHARACTER_SELECT_DURATION_MS: 15000,
  CHOICE_DURATION_MS: 12000,
  BATTLE_DURATION_MS: 16000,
  ROUND_RESULT_DURATION_MS: 4000,
  START_GOLD: 3,
  GOLD_PER_ROUND: 1,
  GOLD_CAP: 10,
  CARD_COST: 3,
  MANA_MAX: 100,
  MANA_REGEN_PER_SEC: 10,
  BATTLE_LOG_RING_SIZE: 300
} as const;
